name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt update
      run: sudo apt update
    - run: sudo apt install libgtk-4-dev
    - run: git clone https://github.com/wmww/gtk4-layer-shell
    - run: sudo apt install meson libwayland-dev libgtk-4-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools valac
    - run: cd gtk4-layer-shell && meson setup -Dexamples=true -Ddocs=true -Dtests=true build && ninja -C build && sudo ninja -C build install && sudo ldconfig
    - run: export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    - run: export LD_LIBRARY_PATH=/usr/local/lib
    - run: cd .. && cargo build --verbose
