name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-lates

    steps:
    - name: Apt update
      run: sudo apt update
    - run: sudo apt install libgtk-4-dev
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: wmww/gtk4-layer-shell
        path: gtk4-layer-shell
    - run: sudo apt install meson libwayland-dev libgtk-4-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools valac
    - run: cd gtk4-layer-shell && meson setup -Dexamples=true -Ddocs=true -Dtests=true build && ninja -C build && sudo ninja -C build install && sudo ldconfig
    - run: export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    - run: export LD_LIBRARY_PATH=/usr/local/lib
    - run: cd ../main && cargo build --verbose
